#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /
    controller: App\Controller\LibraryController::list
    defaults:
        path: /list
        permanent: true

